name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    name: Build and Release on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: macf-linux-x86_64
            archive_name: macf-linux-x86_64.tar.gz
          - os: macos-13
            artifact_name: macf-macos-x86_64
            archive_name: macf-macos-x86_64.tar.gz
          - os: macos-latest
            artifact_name: macf-macos-arm64
            archive_name: macf-macos-arm64.tar.gz
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Build
      run: gcc -o macf main.c
    
    - name: Test executable
      run: |
        ./macf 00:11:22:33:44:55 cisco
        ./macf 00:11:22:33:44:55 dash
    
    - name: Create release package
      run: |
        mkdir -p release/${{ matrix.artifact_name }}
        cp macf release/${{ matrix.artifact_name }}/
        cp macf.1 release/${{ matrix.artifact_name }}/
        cp README.md release/${{ matrix.artifact_name }}/
        cp LICENSE release/${{ matrix.artifact_name }}/
        cd release
        tar -czf ${{ matrix.archive_name }} ${{ matrix.artifact_name }}
    
    - name: Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        files: release/${{ matrix.archive_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
